### PR TITLE
Added fstring and fix ip issue

### PR DESCRIPTION
**Pull request by ghostinlinux**
I replaced normal string formatting to fstring and also fix ip address issue.

### CODE REVIEW

**Comment by sankethj** [comment]
There wasn't any ip issues before. Provide more info. I'll check your code and comeback to you.

**Comment by ghostinlinux** [comment]
> There wasn't any ip issues before. Provide more info. I'll check your code and comeback to you.

In your code only localhost is appering. okk buddy check the code

**Review by sankethj — APPROVED** [review]
**forwarding ip** issue has been resolved, thankyou for your time, working on the project

**Comment by ghostinlinux** [comment]
> **forwarding ip** issue has been resolved, thankyou for your time, working on the project

welcome bro :handshake:

**Pull request merged**
